lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 31556952 # One year in seconds, default is 3600

    api_platform:
        check_path: /auth
        username_path: emailAddress
        password_path: password
