name: Bug Report
description: When a feature is not behaving as expected.
title: "BUG: "
labels: [bug]
assignees: NickStemerdink
body:
  - type: textarea
    id: Describe
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior of the issue you believe to be a bug. You can also provide screenshots for each step or the error.
    placeholder: |
      1. Go to X
      2. Drag and drop this
      3. Click on "this"
      4. Examine error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Description of what you expected to happen.
    validations:
      required: true
